### PR TITLE
pkg/deploy: Add the cluster-monitoring label when creating an Openshift namespace.

### PR DESCRIPTION
**Pull request by timflannagan1**
This would result in the `openshift.io/cluster-monitoring=true` label being added to the `$METERING_NAMESPACE` namespace during an install:
```bash
[tflannag@localhost operator-metering]$ go run cmd/deploy/main.go install
INFO[09-17-2019 13:21:53] Setting the log level to info                 app=deploy
INFO[09-17-2019 13:21:53] Metering Deploy Namespace: metering-tflannag  app=deploy
INFO[09-17-2019 13:21:53] Metering Deploy Platform: openshift           app=deploy
INFO[09-17-2019 13:21:53] Labeling the metering-tflannag namespace with 'openshift.io/cluster-monitoring=true'  app=deploy
INFO[09-17-2019 13:21:53] Created the metering-tflannag namespace       app=deploy
INFO[09-17-2019 13:21:54] Updated the hivetables.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:54] Updated the prestotables.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:54] Updated the storagelocations.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:54] Updated the reports.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:55] Updated the reportqueries.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:55] Updated the reportdatasources.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:56] Updated the meteringconfigs.metering.openshift.io CRD  app=deploy
INFO[09-17-2019 13:21:56] Created the metering deployment               app=deploy
INFO[09-17-2019 13:21:56] Created the metering serviceaccount           app=deploy
INFO[09-17-2019 13:21:56] Created the metering role                     app=deploy
INFO[09-17-2019 13:21:57] Created the metering role binding             app=deploy
INFO[09-17-2019 13:21:57] The metering cluster role already exists      app=deploy
INFO[09-17-2019 13:21:57] The metering cluster role binding already exists  app=deploy
INFO[09-17-2019 13:21:57] Created the MeteringConfig resource           app=deploy
[tflannag@localhost operator-metering]$ k get ns $METERING_NAMESPACE --show-labels
NAME                STATUS   AGE   LABELS
metering-tflannag   Active   16s   openshift.io/cluster-monitoring=true
[tflannag@localhost operator-metering]$ 

```

### CODE REVIEW

**Comment by timflannagan1** [comment]
@chancez good call, updated in the last commit.

**Comment by chancez** [comment]
This isn't bad, but it's a bit verbose and I'm trying to think if this could refactored to be less branch heavy by eg: unconditionally doing the update.

**Comment by timflannagan1** [comment]
@chancez Yeah, I agree - similar to how the other resources are being updated (`MeteringConfig`, CRDs, deployment) I wanted to move away from logging that a resource has been updated when most of the time it hasn't.

I think it's fine for now to mirror the update style/logging of the other resources, and just check that the deploy platform is Openshift, and whether the current namespace object has an initialized labels map.

**Comment by timflannagan1** [comment]
@chancez this can be reviewed again

**Pull request merged**
