### PR TITLE
reporting-operator: fix Prometheus token configuration 

### PR DESCRIPTION
**Pull request by tschuy**

### CODE REVIEW

**Comment by tschuy** [comment]
/hold

Using this for the push to quay ;)

**Comment by pruan-rht** [comment]
@tschuy 3/4 test scenarios passed for me using this PR.  Details of which can be found in the [JIRA](https://jira.coreos.com/browse/MC-469?focusedCommentId=75002&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-75002)

**Comment by tschuy** [comment]
As mentioned on Jira, I think that was more of a question of surfacing errors correctly. I've updated this PR to reflect that.

**Comment by chancez** [comment]
Looks good. Is this ready to merge?

**Comment by chancez** [comment]
So many flakes.
/override ci/prow/e2e-aws-metering

**Comment by pruan-rht** [comment]
@tschuy @chancez yeap, I verified that it failed for the installation with the following error posted in https://jira.coreos.com/browse/MC-469 (which I have marked `DONE`) now.

**Pull request merged**
