### PR TITLE
Edits to OLM install doc

### PR DESCRIPTION
**Pull request by dayleparker**
I work on Koku/Cost Management docs, and this procedure is an essential part of setting up an OCP source. While testing our docs and this procedure, I made a few edits to make this doc align with OpenShift branding standards, and a tiny bit easier to follow. Feedback welcome, I'm a new contributor here!

Summary of changes:
- Added procedural formatting
- minimized wording where possible
- edited product names like OpenShift to have the standard brand capitalization
- a few other various edits

### CODE REVIEW

**Comment by dayleparker** [comment]
Note - I made this WIP as I'm not sure about how to capitalize (or not capitalize) Metering/metering, and it's inconsistent in the doc still. Thoughts welcome...

**Comment by dayleparker** [comment]
Hi @chancez - this is all good for review now, whenever you can. Please let me know what you think.
Cheers, Dayle

**Comment by chancez** [comment]
This looks solid to me. I’ll have some of the other people on the team take a look too.

**Pull request merged**
