### PR TITLE
Added Operator_Metering_Overview.pdf

### PR DESCRIPTION
**Pull request by heoneal**
The current diagram available in the Documentation does not provide the user with an understanding of how the main components of operator metering interact. This is a document that attempts to do so.

### CODE REVIEW

**Comment by chancez** [comment]
@heoneal Is there a way to get access to what generated the PDF? I'd like to be able modify/update it as needed.

**Comment by heoneal** [comment]
Hi Chance,

I am currently traveling on my honeymoon and will get you the documents on
Monday Oct 14

Thanks!

-Holden

**Comment by chancez** [comment]
@heoneal  Congrats! No rush.

**Comment by heoneal** [comment]
Hi Chance,

Since my first pull request, I made enhancements for the following "flows":

1. Data gathering Flow of interactions between reporting-operator, Presto, and Hive
2. Report Gathering Flow of interactions between reporting-operator, Presto, and Hive
3. Flow for ReportDataSource of type PrometheusMetricsImporter
4. Flow for ReportDataSource of type AWSBilling

Please let me know of any updates you make if I've got a misunderstanding somewhere. Thanks!

[Operator_Metering_Layout.pptx](https://github.com/operator-framework/operator-metering/files/3735828/Operator_Metering_Layout.pptx)

**Comment by chancez** [comment]
This looks awesome. Thanks.

**Pull request merged**
